### PR TITLE
Removed from warned list if a player we are tracking logs out after the warning.

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Friendly change, that way they get warned on login instead of instaban.

Previously, if someone logged out due to a warning, then logged back in within their lag machine, next detection cycle they'd get the boot right away. This will give another warning instead.

### CODE REVIEW

**Comment by ttk2** [comment]
wouldn't that mean you could just log really quick all the time to prevent banning?

**Comment by ProgrammerDan** [comment]
I guess if you could figure out the timing of AFKPGC, it'd be possible. 

I'll add a counter, if you "abuse" this too many times in a row it'll just kick you. Let's say 3 warnings, then always ban.

**Comment by ttk2** [comment]
sounds reasonable.

**Comment by ProgrammerDan** [comment]
okay, atm untested (Just putting up on civtest right now) but here's the featureset:

* Offline re-warn on rejoin
* RED ban and warn messages, both in config now.
* increasing ban length based on # of bans issued
* "grace" threshold for those who have never been banned
* config tweaks
* more ideas in the works, these are low-hanging

**Comment by ProgrammerDan** [comment]
I've tested: 

* offline re-warn on join
* RED ban and warning text
* Progressive lengthening of ban based on # issued
* config tweaks

Untested: "Grace" threshold.

@Maxopoly can you look this over and make sure there are no obvious errors or omissions? It's on civtest right now as well. Soon as you give the all clear I see no reason for this not to be merged and deployed.

**Comment by ttk2** [comment]
its a little late to put this online today, so I will do it live tomorrow morning if no more feedback happens.

**Comment by Maxopoly** [comment]
Looks okay, nice work.

**Comment by ttk2** [comment]
staging for prod

**Pull request merged**
