### PR TITLE
Cban integration

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Optional CBan integration (via softdepend). Addresses #26

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
ok to build

**Comment by ProgrammerDan** [comment]
gotta run out, but @Maxopoly if you're on Civtest right now feel free to drop the http://build.civcraft.co/job/AFKGPC-pull/ build there to test, otherwise I'll be back a bit later to test.

**Comment by ProgrammerDan** [comment]
This isn't finding CBan Manager yet. I'll work on it some more later.

**Comment by ProgrammerDan** [comment]
Tested the change on Test -- confirmed working via CBanManagement. 

@ttk2 should be safe to stage; @Maxopoly and @suiradx if you want to look at it and confirm it's good that'd be helpful.

**Comment by Maxopoly** [comment]
Looks fine. Good to merge imo.

**Comment by ProgrammerDan** [comment]
Done. @ttk2 good to stage. Bans shouldn't be perm any more :D

**Pull request merged**
