### PR TITLE
Add option to always warn players

### PR DESCRIPTION
**Pull request by Maxopoly**
Adressing https://github.com/Civcraft/AFK-Player-GC/issues/23

If the tps is good, it counts and just runs the actual BotDetector every X normal runs. 

@ProgrammerDan

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Looks pretty good, do you have shell access to put this on Civtest? I can't remember.

**Comment by Maxopoly** [comment]
I do not

**Comment by ProgrammerDan** [comment]
Can you increment the version to 1.3.5 please?

**Comment by ProgrammerDan** [comment]
Alright it's on civtest.

**Comment by ttk2** [comment]
call for testing or just throw online?

**Comment by ProgrammerDan** [comment]
Oh, sorry, I tested it extensively last night. Works beautifully. Toss it online!

**Comment by ttk2** [comment]
staging for restart then.

**Comment by ProgrammerDan** [comment]
Yeah, I'll give you a new config for it tonight. Finally went through and removed all the things that were listed as tick entities but don't show up on the scanner, I'll put up a merge request for that shortly and send you a version w/ the immunity list.

**Comment by Maxopoly** [comment]
Just tested it as well and came back here to confirm it works, but seems like you were faster than me :D

**Pull request merged**
