### PR TITLE
Added Kick and Ban warning events

### PR DESCRIPTION
**Pull request by TealNerd**

### CODE REVIEW

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
Ok nvm, AFKGPC doesnt have a test build. Should be fine.

**Comment by ProgrammerDan** [comment]
Oh, we should add one of those. Lemme look the commit over.

**Comment by ProgrammerDan** [comment]
Uh, ok, so ... this code introduces some interesting concurrency problems. Let this sit for the moment and I'll take it apart tonight. The bones are good but some of the draping isn't going to work out well, but I think I know what you're aiming for so to address it should be straightforward.

**Pull request closed without merging**
